### ISSUE TITLE
Invalid facilities

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-mobile-plugin-zanzibar#31]
From: "Mkali , Humphrey" <Humphrey.Mkali@thepalladiumgroup.com>
Date: Wednesday, June 6, 2018 at 6:26 AM
To: "Loo, Stephen" <sloo@rti.org>, Mike McKay <mike@vdomck.org>
Cc: Mohamed Ali <alkitwasi@gmail.com>, Abdul-wahiyd Al-mafazy <mtash2@gmail.com>, "Gordon M. Cressman" <gmc@rti.org>
Subject: RE: Invalid facilities

Dear all,
The following HFs are declared invalid in the coconut app (Tablet) despite the fact that they appear in the list of facilities found in the website namely;
1.	Kidimni, Koani, Gana, Modern dispensary and KMKM Kibweni. Also in the coconut app (Tablet) there is a HF called “M and J dispensary” the CORRECT NAME should be “J and M dispensary”
2.	There are two new shehias a)Kijibwe mtu in Central district b) Mtakuja in North A district
Could you please work on these?
Humphrey

**Comment by scloo** [comment]
The problem is we have 2 copies of Facilities in the system. One is the one that is maintained via the Analytics. While the other is a json list named dhis2.json. Looks like Coconut Mobile is using the dhis2 version.

I cannot remember why there are 2 versions. It's a real pain to have to remember to update both versions. And also it is a pain to update the dhis2.json file.

Ideally this dhis2 list should come from the dhis2 server. Right now it s manually maintained. And being unfamiliar with this dhis2.json file, it is easy to make errors when adding or deleting Facilities.

Why are we not using the Facilities list on Analytics, when we do not currently interface with a DHIS2 server?

**Comment by gmcressman** [comment]
Because we will interface with DHIS2. The system must have one or more mechanisms to easily update it's internal organizational hierarchy from DHIS2, and should use it's internal hierarchy consistently throughout the system. For Zanzibar, we needed to add Shehia and Village levels to the DHIS2 Hierarchy. Let's discuss this offline.

**Comment by mikeymckay** [comment]
New reports of invalid facilities:
Dr Metha
Alhajri - South
Tomondo Royal
Kinuni

**Comment by mikeymckay** [comment]
I have replaced the analytics health facility list view with one that displays dhis2 data. Unfortunately dhis2 administrative hierarchy management is not likely to come from dhis2 in Zanzibar anytime soon. But, we are continuing to use the dhis2 format internally. The old analytics facility view was mistakenly showing data that shouldn't be used.
